server:
  port: 8090
  servlet:
    context-path: /test2
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/edu1
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
