//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlowerLauage2018_8_17.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Login> Login { get; set; }
        public virtual DbSet<FlowerData> FlowerData { get; set; }
        public virtual DbSet<FlowerDataDetail> FlowerDataDetail { get; set; }
        public virtual DbSet<ChatData> ChatData { get; set; }
        public virtual DbSet<ServiceData> ServiceData { get; set; }
        public virtual DbSet<PlantData> PlantData { get; set; }
        public virtual DbSet<AnswerData> AnswerData { get; set; }
    }
}
