//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlowerLauage2018_8_17.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlowerData
    {
        public string ID { get; set; }
        public string Introduction { get; set; }
        public string Techniques { get; set; }
        public string Alias { get; set; }
        public string Picture { get; set; }
    }
}
