//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlowerLauage2018_8_17.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlantData
    {
        public string PlantID { get; set; }
        public string UserID { get; set; }
        public string Name { get; set; }
        public string Kind { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public int OrderID { get; set; }
    }
}
